replicaCount: 1

image:
  repository: ghcr.io/yourorg/placeholder
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  hosts: []
  annotations: {}

resources: {}

env: []
command: []
args: []

readinessProbe: {}
livenessProbe: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
